### PR TITLE
Add Compressed Out Directory

### PR DESCRIPTION
**Pull request by bh2smith**
In preparation to archive this repo, we add the `sha256sum.txt` file containing hashes of every data file fetched and used to construct the token allocation files.

Test Plan: Now that the trades table is stored as fixed data the sha hash of this directory should be fixed.

```sh
python -m src.main    <------ This may take about 13 minutes to generate!
shasum -a 256 out/*.csv
```

Compare this with the `sha256sum.txt` file committed here.

### CODE REVIEW

**Comment by nlordell** [comment]
Thanks for the detailed test plan! What you could also do instead of adding this as a PR to the file is instead include it as an "Release artifact" - this makes it show up in the "Releases" page for the repo but then you don't need to pull an 8MB file when you do a `git clone`.

I'm fine either way though.

**Comment by nlordell** [comment]
Hmm, I got a different checksum:
```
% zip -vr out.zip out/ -x "*.DS_Store"
8796c1ec0f6b99b1ec2d7477f3649b4b77eaf7e0278e9b9b8b35c96d96ec4162  out.zip
```

Maybe ZIPs depend on some runtime magic? Here are the checksums of all my files:
```
% shasum -a 256 out/*.csv
5db5e19335ac7b661c6bd1c7705f36aeff05402d720878c51199c25d46c97c81  out/allocations-gchain.csv
299b43de73d13bedda8937f6a284d79310a47539f52fe8c9b61a91e812336d18  out/allocations-holder.csv
382cbdf4ca33c3c5c6c580d1b5a5384e34f513218b32f8d15a1669f3d4ce9277  out/allocations-mainnet.csv
c89df4dd91118c307652179a529f731d8ffd233d7468f1caa0b0cb1e8c0f8826  out/allocations-poap.csv
32c776f13f994b5f64922e1a3accc4a9da9c9a5f26fdfbcbcb8fb75e3a7a4314  out/allocations-trader-consolation.csv
dd631659482082d2173f90385f36be528fcf4f511ef81d208701bff7fc2e3af7  out/allocations-trader-primary.csv
67780a2e5ec62d660f687bb7608d42610d7af45b30c561e99ce3cee50da42919  out/allocations.csv
34b23af834ca2f86a87deff0fd27eeb08eb597922e8f1477b6fd7c4012f47fb7  out/combined-consolation-trader-data.csv
18ac06a4f979607f7ab950a0a6c222758be934dab73ac35c531394d892d40fff  out/combined-holders.csv
2bb596f1eae2e4dbabe82a68a2287d6e60cb1579a01b89ac6f83f96ab9aa0108  out/combined-primary-trader-data.csv
42cb93aae6dc283da48cce3b090d4fd2d6b5fff1048fca75aa62208cad9afe75  out/combined-user-options.csv
d51ddf4d620d4238afa339021a458d3e517b2a4d346760b7856845c2cb457587  out/gchain-alpha-traders.csv
f347a09cce229790de74e540dd6e0c40a8a55516b107e803e062b0703da0f2de  out/gchain-gno-holders.csv
28b588449630b166ffc0edab03813e2f62ecd2b0fc1d90889b40fdec296e890f  out/gchain-gno-stakers.csv
9a661ad5678742a2758a172de5f4abf34b9683a643fecfd501809def28cd4b5f  out/gchain-holders-master.csv
74a1d7938a803bef893b7b6b1848e8c0b6c0814ec149449865ee3ad0a5b20966  out/gchain-lp-holders.csv
3666ed3b917c035b2fa2cdb77096b3a326484b9134cbae0f0091e75bffdaf2ba  out/mainnet-alpha-traders.csv
ff419d75d6eb315720074bdde63b3573d9a826df47f16cec24023c17107c9e17  out/mainnet-balancer-gno.csv
333f8b76c2f8bedc1e3b9b665349713ebf681f022f47c689ac0dfdf2970bb0f7  out/mainnet-gno-holders.csv
ba9340fbd634c76f28b881f9662c626196edf51a672d28394455bba2980bff8e  out/mainnet-holders-master.csv
754d70f0c907e052e0c462e21cb6bbada3744e3de74418c7a2d47896fb22f75c  out/mainnet-lp-holders.csv
d721de2c21548e874d952b8200b614db100bf03ec0efa9268ec5b706939c88db  out/mainnet-univ3-holders.csv
```

**Comment by nlordell** [comment]
Also another tip - you can use the `shasum` command to generate a "sum-file" that can be checked (this might be useful to also include in the distribution as well):

```
% shasum -a 256 out/*.csv > sha256sum.txt
% shasum -c sha256sum.txt 
out/allocations-gchain.csv: OK
out/allocations-holder.csv: OK
out/allocations-mainnet.csv: OK
out/allocations-poap.csv: OK
out/allocations-trader-consolation.csv: OK
out/allocations-trader-primary.csv: OK
out/allocations.csv: OK
out/combined-consolation-trader-data.csv: OK
out/combined-holders.csv: OK
out/combined-primary-trader-data.csv: OK
out/combined-user-options.csv: OK
out/gchain-alpha-traders.csv: OK
out/gchain-gno-holders.csv: OK
out/gchain-gno-stakers.csv: OK
out/gchain-holders-master.csv: OK
out/gchain-lp-holders.csv: OK
out/mainnet-alpha-traders.csv: OK
out/mainnet-balancer-gno.csv: OK
out/mainnet-gno-holders.csv: OK
out/mainnet-holders-master.csv: OK
out/mainnet-lp-holders.csv: OK
out/mainnet-univ3-holders.csv: OK
% echo foo >> out/mainnet-univ3-holders.csv 
% shasum -c sha256sum.txt
...
out/mainnet-univ3-holders.csv: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```

**Comment by bh2smith** [comment]
Thanks @nlordell - could you share the one differing file? This may be the result of them having updated their subgraph recently. 

> Also another tip - you can use the shasum command to generate a "sum-file" that can be checked (this might be useful to also include in the distribution as well):

I am also not sure I fully understand what you are suggesting here.

**Comment by nlordell** [comment]
> could you share the one differing file?

Do you mean `out/mainnet-univ3-holders.csv: FAILED`? This was just my example of using how modifying the file would make `shasum -c sha256sums.txt` detect the change.

Attached are my checksums. You can just place it in your `out/` directory and run `shasum -c sha256sum.txt` to see which files are different.

[sha256sum.txt](https://github.com/cowprotocol/token-allocation/files/8412967/sha256sum.txt)

**Comment by bh2smith** [comment]
I mean actually share the file(s) that is/are differing so I can see where. If you are saying that the uni-v3 file is not the differing file and that was just an example, then I would request that you not use the actual file names in a hypothetical example. I had already started investigating why the univ3 file is different. 

Anyway, I'll check the hashes you gave me and come back with an explicit request for which files I would need. 

Also, I like you point of attaching it in a release instead of here.

**Comment by nlordell** [comment]
Sorry for the confusion around the example. I just tried to illustrate what would happen if you:
1. Generated a checksum file with `shasum -a 256 out/*.csv > sha256sum.txt`
2. Modified one of the files with `echo foo >> out/mainnet-univ3-holders.csv`
3. Verified the checksums with `shasum -c sha256sum.txt`

All of these commands should have been included in the code block ☝️.

As for checking the hashes, it can be done with `shasum -c sha256sum.txt` as in the example.

**Comment by nlordell** [comment]
Total brain-fart on my part - for some reason I thought I couldn't do the sha256 verification on files individually without having your checksums - but I didn't realize that I can just use the `out.zip` file that was pushed with this PR and compare with the checksums I generate:

```shell
python -m src.main
shasum -a 256 out/*.csv > sha256sum.txt
rm -rf out/
unzip out.zip
shasum -c sha256sum.txt
```

Results in
```
out/allocations-gchain.csv: OK
out/allocations-holder.csv: OK
out/allocations-mainnet.csv: OK
out/allocations-poap.csv: OK
out/allocations-trader-consolation.csv: OK
out/allocations-trader-primary.csv: OK
out/allocations.csv: OK
out/combined-consolation-trader-data.csv: OK
out/combined-holders.csv: OK
out/combined-primary-trader-data.csv: OK
out/combined-user-options.csv: OK
out/gchain-alpha-traders.csv: OK
out/gchain-gno-holders.csv: OK
out/gchain-gno-stakers.csv: OK
out/gchain-holders-master.csv: OK
out/gchain-lp-holders.csv: OK
out/mainnet-alpha-traders.csv: OK
out/mainnet-balancer-gno.csv: OK
out/mainnet-gno-holders.csv: OK
out/mainnet-holders-master.csv: OK
out/mainnet-lp-holders.csv: OK
out/mainnet-univ3-holders.csv: OK
```

So all the files match despite the ZIP directory I generate being different. The question for the release, should we include the checksum of the individual CSV files or the whole ZIP directory?

**Comment by nlordell** [comment]
Symbolically approving the PR, but I don't think we should merge it because I think we should include this as a release instead.

**Review by nlordell — APPROVED** [review]

**Comment by bh2smith** [comment]
We could commit the file `sha256sum.txt` that you have been referring to here and I will attach the zipped out directory as a release after this is merged. Sound good to you?

**Comment by nlordell** [comment]
> after this is merged

Personally, I would actually _not_ merge the PR. It adds a 8MB file that needs to be downloaded on `git clone` which I would argue is not super helpful. Instead I would just create a new release and attack the `out.zip` and `sha256sum.txt` files to it.

That being said, since we are archiving this repo, its not super important to watch for repo-size.

**Comment by bh2smith** [comment]
You will notice that I have removed the zip file here and replaced it with the sha hashes. My point is to merge this with the hashes and **NOT** the zip file (as you have already mentioned a few times). I will attach the zip file as a release - also as you have suggested.

**Comment by nlordell** [comment]
Makes sense. I missed the part that the `out.zip` would be removed.

**Comment by bh2smith** [comment]
Release is published here:
https://github.com/cowprotocol/token-allocation/releases/tag/v1.0.0

**Pull request merged**
